name = "lustre_ui"
version = "0.4.0"
description = "A collection of components and design tokens for building Lustre apps."
target = "javascript"

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre_ui" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["internals/*", "lustre/ui/internals"]
gleam = ">= 0.33.0"

[dependencies]
gleam_community_colour = "~> 1.4"
gleam_json = "~> 1.0"
gleam_stdlib = "~> 0.34"
lustre = "~> 3.0 or ~> 4.0"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 1.0"
